apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    resources.limits.cpu: "2"
    resources.limits.memory: "2Gi"
    resources.requests.cpu: "1"
    resources.requests.memory: "1Gi"
    resources.limits.pid: "1000"
spec:
  runtimeClassName: resource-slot
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
      requests:
        cpu: "1"
        memory: "1Gi"
  restartPolicy: Never
